src/EdNexusData.Broker.Web/Controllers/API/MessagesController.cs
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using EdNexusData.Broker.Core.Interfaces;
using EdNexusData.Broker.Core.Services;

namespace EdNexusData.Broker.Controllers.Api;

[AllowAnonymous]
[ApiController]
[Route("api/v1/messages")]
public class MessagesController : Controller
{
    private readonly INowWrapper nowWrapper;
    private readonly MessageService messageService;

    public MessagesController(INowWrapper nowWrapper, MessageService messageService)
    {
        this.nowWrapper = nowWrapper;
        this.messageService = messageService;
    }
    
    [HttpGet]
    public IActionResult Index()
    {
        return Ok();
    }

    [HttpPost]
    public async Task<IActionResult> Receive()
    {
        try
        {
            using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
            {
                string rawValue = await reader.ReadToEndAsync();
                var message = await messageService.CreateFromAPIRequest(rawValue);
                return Created("messages", message.RequestId);
            }
        }
        catch(Exception ex)
        {
            return StatusCode((int)HttpStatusCode.InternalServerError, $"{ex.Message}\n\n{ex.StackTrace}");
        }
    }
}

src/EdNexusData.Broker.Web/Controllers/Request/OutgoingController.cs
// Copyright: 2023 Education Nexus Oregon
// Author: Makoa Jacobsen, makoa@makoajacobsen.com

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EdNexusData.Broker.Web.Models.OutgoingRequests;
using EdNexusData.Broker.Web.Models.Paginations;
using EdNexusData.Broker.Web.Specifications;
using System.Security.Claims;
using Ardalis.Specification;
using EdNexusData.Broker.Web.ViewModels.OutgoingRequests;
using EdNexusData.Broker.Web.Services.PayloadContents;
using static EdNexusData.Broker.Web.Constants.Claims.CustomClaimType;
using EdNexusData.Broker.Web.Helpers;
using EdNexusData.Broker.Web.Extensions.Genders;
using Ardalis.GuardClauses;
using System.Text.Json;
using EdNexusData.Broker.Web.Utilities;
using EdNexusData.Broker.Web.Constants.DesignSystems;
using EdNexusData.Broker.Core.Jobs;
using EdNexusData.Broker.Common.Payloads;
using EdNexusData.Broker.Common.Jobs;
namespace EdNexusData.Broker.Web.Controllers;

[Authorize(Policy = TransferOutgoingRecords)]
[Authorize(Policy = "RecordAllowed")]
public class OutgoingController : AuthenticatedController<OutgoingController>
{
    private readonly IRepository<Request> _outgoingRequestRepository;
    private readonly IRepository<PayloadContent> _payloadContentRepository;
    private readonly IRepository<EducationOrganization> _educationOrganizationRepository;
    private readonly IPayloadContentService _payloadContentService;
    private readonly FocusHelper _focusHelper;
    private readonly ICurrentUser _currentUser;
    private readonly ManifestService _manifestService;
    private readonly JobService _jobService;
    private readonly CurrentUserHelper currentUserHelper;

    public OutgoingController(
        IHttpContextAccessor httpContextAccessor,
        IRepository<Request> outgoingRequestRepository,
        IRepository<PayloadContent> payloadContentRepository,
        IRepository<EducationOrganization> educationOrganizationRepository,
        IPayloadContentService payloadContentService,
        FocusHelper focusHelper,
        ICurrentUser currentUser,
        ManifestService manifestService,
        JobService jobService,
        CurrentUserHelper currentUserHelper)
    {
        _outgoingRequestRepository = outgoingRequestRepository;
        _payloadContentRepository = payloadContentRepository;
        _educationOrganizationRepository = educationOrganizationRepository;
        _payloadContentService = payloadContentService;
        _focusHelper = focusHelper;
        _currentUser = currentUser;
        _manifestService = manifestService;
        _jobService = jobService;
        this.currentUserHelper = currentUserHelper;
    }

    public async Task<IActionResult> Index(
      OutgoingRequestModel model,
      CancellationToken cancellationToken)
    {
        RefreshSession();

        var searchExpressions = model.BuildSearchExpressions();

        searchExpressions.Add(x => x.IncomingOutgoing == IncomingOutgoing.Outgoing);

        var schools = await _focusHelper.GetFocusedSchools();
        searchExpressions.Add(x => schools.Contains(x.EducationOrganization!));

        var sortExpression = model.BuildSortExpression();

        var specification = new SearchableWithPaginationSpecification<Request>.Builder(model.Page, model.Size)
            .WithAscending((model.SortDir != null) ? model.IsAscending : false)
            .WithSortExpression(sortExpression)
            .WithSearchExpressions(searchExpressions)
            .WithIncludeEntities(builder => builder
                .Include(outgoingRequest => outgoingRequest.EducationOrganization)
                .ThenInclude(educationOrganization => educationOrganization!.ParentOrganization)
                )
            .Build();

        var totalItems = await _outgoingRequestRepository.CountAsync(
            specification,
            cancellationToken);

        var outgoingRequests = await _outgoingRequestRepository.ListAsync(
            specification,
            cancellationToken);

        var outgoingRequestViewModels = outgoingRequests
            .Select(outgoingRequest => new OutgoingRequestViewModel(outgoingRequest, currentUserHelper.ResolvedCurrentUserTimeZone()));

        totalItems = outgoingRequestViewModels.Count();

        if (!string.IsNullOrWhiteSpace(model.SearchBy))
        {
            outgoingRequestViewModels = outgoingRequestViewModels
                .Where(request => request.Student?.ToLower().Contains(model.SearchBy) is true || request.ReceivingSchool.ToLower().Contains(model.SearchBy)
                 || request.ReceivingSchool.ToLower().Contains(model.SearchBy));
            totalItems = outgoingRequestViewModels.Count();
        }

        var result = new PaginatedViewModel<OutgoingRequestViewModel>(
            outgoingRequestViewModels,
            totalItems,
            model.Page,
            model.Size,
            model.SortBy,
            model.SortDir,
            model.SearchBy);

        return View(result);
    }

    [Route("/outgoing-requests/edit/{id:guid}")]
    public async Task<IActionResult> Update(Guid id, Guid? jobId)
    {
        var outgoingRequest = await _outgoingRequestRepository.FirstOrDefaultAsync(new RequestByIdWithPayloadContents(id));
        if (outgoingRequest is null) return NotFound();

        if (outgoingRequest.RequestStatus != RequestStatus.Extracted)
        {
            ViewBag.JobId = jobId;
        }
        
        var viewModel = new CreateOutgoingRequestViewModel()
        {
            RequestId = outgoingRequest.Id,
            RequestReceived = outgoingRequest.CreatedAt,
            StudentUniqueId = outgoingRequest.Student?.Student?.StudentNumber,
            Additional = JsonSerializer.Serialize(outgoingRequest.Student?.Connectors),
            FirstName = outgoingRequest.Student?.Student?.FirstName,
            MiddleName = outgoingRequest.Student?.Student?.MiddleName,
            LastSurname = outgoingRequest.Student?.Student?.LastName,
            Grade = outgoingRequest.Student?.Student?.Grade,
            Gender = outgoingRequest.Student?.Student?.Gender,
            BirthDate = outgoingRequest.Student?.Student?.Birthdate?.ToString("yyyy-MM-dd"),
            ReceivingStudent = outgoingRequest.RequestManifest?.Student,
            ReceivingDistrict = outgoingRequest.RequestManifest?.From?.District,
            ReceivingSchool = outgoingRequest.RequestManifest?.From?.School,
            ReceivingSchoolContact = outgoingRequest.RequestManifest?.From?.Sender,
            ReceivingNotes = outgoingRequest.RequestManifest?.Note,
            ReleasingNotes = outgoingRequest.ResponseManifest?.Note,
            Contents = outgoingRequest.ResponseManifest?.Contents?.Select(x => x.FileName.ToString()).ToList(),
            RequestStatus = outgoingRequest.RequestStatus,
            Genders = Genders.GetSelectList(),
            ReceivingAttachments = outgoingRequest.PayloadContents?.Where(x => outgoingRequest.RequestManifest!.Contents!.Select(y => y.FileName).Contains(x.FileName)).ToList(),
            ReleasingAttachments = (outgoingRequest.ResponseManifest is not null) ? outgoingRequest.PayloadContents?.Where(x => outgoingRequest.ResponseManifest!.Contents!.Select(y => y.FileName).Contains(x.FileName)).ToList() : null,
            DraftAttachments = outgoingRequest.PayloadContents?.Where(x => x.MessageId == null).ToList()
        };

        return View(viewModel);
    }

    [HttpPut]
    [Authorize]
    [ValidateAntiForgeryToken]
    [Route("/outgoing-requests/edit/{id:guid}")]
    public async Task<IActionResult> Update(CreateOutgoingRequestViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            var userId = Guid.Parse(User.FindFirstValue(claimType: ClaimTypes.NameIdentifier)!);

            var outgoingRequest = await _outgoingRequestRepository.GetByIdAsync(viewModel.RequestId);

            Guard.Against.Null(outgoingRequest);

            var student = new Student()
            {
                LastName = viewModel.LastSurname,
                FirstName = viewModel.FirstName,
                MiddleName = viewModel.MiddleName,
                Gender = viewModel.Gender,
                Grade = viewModel.Grade,
                Birthdate = (viewModel.BirthDate is not null) ? DateOnly.Parse(viewModel.BirthDate) : null,
                StudentNumber = viewModel.StudentUniqueId
            };

            // Resolve Student
            var jsonConnector = (viewModel.Additional is not null) ? JsonSerializer.Deserialize<Dictionary<string, object>>(viewModel.Additional) : null;

            outgoingRequest.Student = new StudentRequest()
            {
                Student = student,
                Connectors = (jsonConnector is not null) ? new Dictionary<string, object>
                    { 
                        [jsonConnector.Keys.First()] = jsonConnector.GetValueOrDefault(jsonConnector.Keys.First())!
                    } : null
            };

            outgoingRequest.ResponseManifest = new Manifest() {
                RequestType = typeof(StudentCumulativeRecordPayload).FullName!,
                Student = student,
                Note = viewModel.ReleasingNotes,
                To = new RequestAddress()
                {
                    District = outgoingRequest?.RequestManifest?.From?.District,
                    School = outgoingRequest?.RequestManifest?.From?.School
                }
            };

            await _outgoingRequestRepository.UpdateAsync(outgoingRequest!);

            await _payloadContentService.AddPayloadContentsAsync(viewModel.Files, viewModel.RequestId);

            TempData[VoiceTone.Positive] = $"Updated request for {viewModel.FirstName} {viewModel.LastSurname} ({outgoingRequest!.Id}).";

            return RedirectToAction(nameof(Update), new { requestId = outgoingRequest.Id });
        }

        return View(viewModel);
    }

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> ViewAttachment(Guid id)

src/EdNexusData.Broker.Web/Views/Outgoing/Update.cshtml
@model EdNexusData.Broker.Web.ViewModels.OutgoingRequests.CreateOutgoingRequestViewModel
@using EdNexusData.Broker.Core.Extensions
@{
    // Copyright: 2023 Education Nexus Oregon
    // Author: Makoa Jacobsen, makoa@makoajacobsen.com
    ViewData["Title"] = "Outgoing Record Request Details";
    Layout = "_AuthenticatedLayout";
    ViewData["FocusBar"] = true;
    ViewData["FocusBarReadOnly"] = true;
}

<form method="post" asp-action="Update" autocomplete="off">
  <input type="hidden" name="_METHOD" value="PUT" />
  <partial name="_form" for="@Model" />
</form>

<partial name="_file" for="@Model" />

@section HeaderAction
{
  <div class="flex space-x-4">
  @if(ViewBag.JobId is not null && ViewBag.JobId.ToString() != "")
  {
  <div x-data="preparingIndex">
    <span x-text="status">@Model.RequestStatus.GetDescription()</span>
  </div>
  } 
  else
  {
    <div>@Model.RequestStatus.GetDescription()</div>
  }
  @if ((Model.RequestStatus == EdNexusData.Broker.Common.Jobs.RequestStatus.Received 
       || Model.RequestStatus == EdNexusData.Broker.Common.Jobs.RequestStatus.Extracted  
       || Model.RequestStatus == EdNexusData.Broker.Common.Jobs.RequestStatus.Reopened
      )
   && Model.StudentUniqueId is not null)
  {
    <div>
    <form method="post" asp-action="Load" asp-route-id="@Model.RequestId" autocomplete="off">
      <input type="hidden" name="_METHOD" value="PUT" />
      <button
        type="submit"
        class="relative inline-flex items-center rounded-md bg-tertiary-700 px-3 py-2 text-center text-sm font-semibold ring-1 ring-inset ring-tertiary-800 text-white shadow-sm hover:bg-tertiary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tertiary-700 focus:z-10"
      >Extract</button>
    </form>
    </div>
  } 
  @if (Model.RequestStatus == EdNexusData.Broker.Common.Jobs.RequestStatus.Extracted) {
    <div>
    <form method="post" asp-action="Send" asp-route-id="@Model.RequestId" autocomplete="off">
      <input type="hidden" name="_METHOD" value="PUT" />
      <button
        type="submit"
        class="relative inline-flex items-center rounded-md bg-tertiary-700 px-3 py-2 text-center text-sm font-semibold ring-1 ring-inset ring-tertiary-800 text-white shadow-sm hover:bg-tertiary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tertiary-700 focus:z-10"
      >Transmit</button>
    </form>
    </div>
  }
  </div>
}

@section scripts
{
<script>
  document.addEventListener('alpine:init', () => {

    Alpine.data('preparingIndex', () => ({
      status: "Loading...",
      interval: null,
      fetchData: null,
      initFetchData: function() {
        this.fetchData = async () => {
          try {
            const response = await fetch('/api/v1/jobs?jobId=@ViewBag.JobId');
            const data = await response.json();
            //console.log(data);
            this.status = data.workerState;
            //console.log("Worker State: " + data.workerState);

            //console.log("Job Status: " + data.jobStatus);
            if (data.jobStatus == 2)
            {
              //console.log("Inside job status");
              location.reload();
              clearInterval(this.interval);
            }

          } catch (error) {
            console.error('Error fetching status:', error);
            clearInterval(this.interval);
          }
        };
      },
      init() {
        this.initFetchData();
        //console.log("Called startPolling and about to call setInterval");
        this.interval = setInterval(this.fetchData, 2000); // Poll every 2 seconds (adjust as needed)
        //this.status = "Called setInternal";
        //console.log("Called setInterval");
        
      },
      destroy() {
          // Detach the handler, avoiding memory and side-effect leakage
          clearInterval(this.interval);
      },
    }))
    
  });
</script>
}

src/EdNexusData.Broker.Web/Views/Outgoing/_file.cshtml
@model EdNexusData.Broker.Web.ViewModels.OutgoingRequests.CreateOutgoingRequestViewModel
@using static EdNexusData.Broker.Web.Constants.Claims.CustomClaimType;

<div class="my-4">
    <div class="px-4 sm:px-0">
        <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
            <div class="px-4 py-6 sm:p-8 grid gap-8">
                <div class="grid grid-cols-1 gap-6 sm:grid-cols-6">
                    <div class="sm:col-span-3">
                        <div class="block text-sm font-medium leading-6 text-gray-900">
                            <div class="grid grid-cols-6 gap-0.5">
                            <div class="col-span-5">Attachments</div>
                            <div class="col-span-1">
                            @if(Model.DraftAttachments is not null && Model.DraftAttachments.Count > 0) {
                                <form method="post" asp-action="DeleteAllAttachments" autocomplete="off">
                                <input type="hidden" name="_METHOD" value="DELETE" />
                                <input asp-for="RequestId" type="hidden" />
                                <button type="submit" class="-m-2.5 flex items-center justify-center bg-white p-2.5 text-gray-400 hover:text-gray-500">
                                    <span class="sr-only">Delete All Attachments</span>
                                    <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z" clip-rule="evenodd" />
                                    </svg>
                                </button>
                                </form>
                            }
                            </div>
                            </div>
                        </div>
                        <div class="mt-2">
                            <div class="grid grid-cols-6 gap-0.5">
                                @if(Model.ReleasingAttachments is not null)
                                @foreach(var payloadContent in Model.ReleasingAttachments)
                                {
                                    <div class="col-span-5">
                                      <div class="flex items-center">
                                        <svg class="h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z" clip-rule="evenodd"></path>
</svg>
                                       <div class="p-1"><a target="_blank" asp-action="ViewAttachment" asp-route-id="@payloadContent.Id">
                                        @payloadContent.FileName
                                        </a>
                                        </div>
                                       </div>
                                    </div>
                                }
                                @if(Model.DraftAttachments is not null)
                                @foreach(var payloadContent in Model.DraftAttachments)
                                {
                                    <div class="col-span-5">
                                      <div class="flex items-center">
                                        <svg class="h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z" clip-rule="evenodd"></path>
</svg>
                                       <div class="p-1 truncate"><a target="_blank" asp-action="ViewAttachment" asp-route-id="@payloadContent.Id" class="">@payloadContent.FileName</a></div>
                                       </div>
                                    </div>
                                    <div class="col-span-1">
                                        <form method="post" asp-action="DeleteAttachment" autocomplete="off">
                                        <input type="hidden" name="_METHOD" value="DELETE" />
                                        <input asp-for="RequestId" type="hidden" />
                                        <input type="hidden" name="PayloadContentId" value="@payloadContent.Id" />
                                        <button type="submit" class="-m-2.5 flex items-center justify-center bg-white p-2.5 text-gray-400 hover:text-gray-500">
                                            <span class="sr-only">Delete Attachment</span>
                                            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                <path fill-rule="evenodd" d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z" clip-rule="evenodd" />
                                            </svg>
                                        </button>
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="sm:col-span-3">
                        <label class="block text-sm font-medium leading-6 text-gray-900">Upload File(s)</label>
                        <form method="post" asp-action="UploadAttachment" autocomplete="off" enctype="multipart/form-data">
                        <div class="mt-2">
                            <div class="flex justify-between w-full">
                                <input id="dropzone-file" type="file" multiple="true" name="files" />
                                <input asp-for="RequestId" type="hidden" />
                                <button type="submit" class="relative inline-flex items-center rounded-md bg-tertiary-700 px-3 py-2 text-center text-sm font-semibold ring-1 ring-inset ring-tertiary-800 text-white shadow-sm hover:bg-tertiary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tertiary-700 focus:z-10">Upload</button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/EdNexusData.Broker.Web/Views/Outgoing/header.cshtml
  @using static EdNexusData.Broker.Web.Constants.Claims.CustomClaimType;
  <header class="relative isolate">
    <div class="absolute inset-0 -z-10 overflow-hidden" aria-hidden="true">
      <div class="absolute left-16 top-full -mt-16 transform-gpu opacity-50 blur-3xl xl:left-1/2 xl:-ml-80">
        <div class="aspect-[1154/678] w-[72.125rem] bg-gradient-to-br from-secondary-500 to-secondary-100" style="clip-path: polygon(100% 38.5%, 82.6% 100%, 60.2% 37.7%, 52.4% 32.1%, 47.5% 41.8%, 45.2% 65.6%, 27.5% 23.4%, 0.1% 35.3%, 17.9% 0%, 27.7% 23.4%, 76.2% 2.5%, 74.2% 56%, 100% 38.5%)"></div>
      </div>
      <div class="absolute inset-x-0 bottom-0 h-px bg-gray-900/5"></div>
    </div>

    <div class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
      <div class="mx-auto flex max-w-2xl items-center justify-between gap-x-8 lg:mx-0 lg:max-w-none">
        <div class="flex items-center gap-x-6">
          <img src="~/images/Final-Education-Nexus-ICON-png.png" alt="@Model.FromDistrict" class="h-16 w-16 flex-none rounded-full ring-1 ring-gray-900/10">
          <h1>
            <div class="text-sm leading-6 text-gray-500">Student Unique ID: <span class="text-gray-700">@Model.StudentUniqueId</span></div>
            <div class="mt-1 text-base font-semibold leading-6 text-gray-900">@Model.FirstName @Model.MiddleName @Model.LastSurname</div>
          </h1>
        </div>
        <div class="flex items-center gap-x-4 sm:gap-x-6">
          <a
            asp-controller="Outgoing"
            asp-action="Index"
            asp-authorize
            asp-policy="@TransferOutgoingRecords"
            class="text-sm font-semibold leading-6 text-gray-900"
          >
            Back to list
          </a>
        </div>
      </div>
    </div>
  </header>

src/EdNexusData.Broker.Web/Views/Outgoing/message.cshtml
<h2 class="text-sm font-semibold leading-6 text-gray-900">Messages</h2>
        <ul role="list" class="mt-6 space-y-6">
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <p class="flex-auto py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Luis Ruiz</span> created the request.</p>
            <time datetime="2023-01-23T10:32" class="flex-none py-0.5 text-xs leading-5 text-gray-500">2d ago</time>
          </li>
          <li class="relative flex gap-x-4">
            <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
              <div class="w-px bg-gray-200"></div>
            </div>
            <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
              <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
            </div>
            <div class="flex-auto rounded-md p-3 ring-1 ring-inset ring-gray-200">
              <div class="flex justify-between gap-x-4">
                <div class="py-0.5 text-xs leading-5 text-gray-500"><span class="font-medium text-gray-900">Luis Ruiz</span> commented</div>
                <time datetime="2023-01-23T15:56" class="flex-none py-0.5 text-xs leading-5 text-gray-500">1d ago</time>
              </div>
              <p class="text-sm leading-6 text-gray-500">Called student, they reassured me the forms would be ready by the 30th.</p>
            </div>
          </li>
        </ul>

        <div class="mt-6 flex gap-x-3">
          <div class="absolute left-0 top-0 flex w-6 justify-center -bottom-6">
            <div class="w-px bg-gray-200"></div>
          </div>
          <div class="relative flex h-6 w-6 flex-none items-center justify-center bg-white">
            <div class="h-1.5 w-1.5 rounded-full bg-gray-100 ring-1 ring-gray-300"></div>
          </div>
          <div class="relative grid gap-2 flex-1">
            <div class="overflow-hidden rounded-lg pb-12 shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-tertiary-600">
              <label for="message" class="sr-only">Add your message</label>
              <textarea id="message" class="block w-full resize-none border-0 bg-transparent py-1.5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Add your message..."></textarea>
            </div>
            <div class="text-right">
              <button type="button" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Message</button>
            </div>
          </div>
        </div>