src/EdNexusData.Broker.Web/Models/JobViewModel.cs
using EdNexusData.Broker.Common.Jobs;
using EdNexusData.Broker.Core.Worker;

namespace EdNexusData.Broker.Web.Models;

public class JobViewModel
{
    public Guid? JobId { get; set; }

    public string QueuedDateTime { get; set; } = default!;

    public string? StartDateTime { get; set; }

    public string? FinishDateTime { get; set; }

    public JobStatus? JobStatus { get; set; }

    public string? WorkerState { get; set; }

    public string? WorkerInstance { get; set; }

    public string? JobType { get; set; }

    public string? User { get; set; }

    public JobViewModel(Job job, TimeZoneInfo timezone)
    {
        JobId = job.Id;

        QueuedDateTime = TimeZoneInfo.ConvertTimeFromUtc(job.QueueDateTime.DateTime, timezone).ToString("M/dd/yyyy h:mm:ss tt");

        StartDateTime = (job.StartDateTime is not null) 
            ? TimeZoneInfo.ConvertTimeFromUtc(job.StartDateTime.Value.DateTime, timezone).ToString("M/dd/yyyy h:mm:ss tt") 
            : null;
        
        FinishDateTime = (job.FinishDateTime is not null) 
            ? TimeZoneInfo.ConvertTimeFromUtc(job.FinishDateTime.Value.DateTime, timezone).ToString("M/dd/yyyy h:mm:ss tt") 
            : null;

        JobStatus = job.JobStatus;
        WorkerInstance = job.WorkerInstance;
        if (job.WorkerState?.Length > 50)
        {
            WorkerState = job.WorkerState?.Substring(0, 50) + "...";
        }
        else
        {
            WorkerState = job.WorkerState;
        }
        
        JobType = job.JobType;

        User = job.InitiatedUser?.LastFirstName;
    }
}

src/EdNexusData.Broker.Web/Controllers/API/JobsController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EdNexusData.Broker.Core.Worker;

namespace EdNexusData.Broker.Controllers.Api;

[Authorize]
[ApiController]
[Route("api/v1/jobs")]
public class ApiJobsController : Controller
{
    private readonly JobStatusService<ApiJobsController> _jobStatusService;

    public ApiJobsController(JobStatusService<ApiJobsController> jobStatusService)
    {
        _jobStatusService = jobStatusService;
    }

    [HttpGet]
    public async Task<IActionResult> Index(Guid? jobId)
    {
        if (jobId.HasValue == false)
        {
            return BadRequest("Job ID is required.");
        }

        try
        {
            var results = await _jobStatusService.Get(jobId.Value);

            return Ok(results);
        }
        catch(Exception ex)
        {
            return StatusCode((int)HttpStatusCode.InternalServerError, $"{ex.Message}\n\n{ex.StackTrace}");
        }
    }

}

src/EdNexusData.Broker.Web/Controllers/API/RequestsController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EdNexusData.Broker.Web.Utilities;
using EdNexusData.Broker.Core.Services;

namespace EdNexusData.Broker.Controllers.Api;

[AllowAnonymous]
[ApiController]
[Route("api/v1/requests")]
public class RequestsController : Controller
{
    private readonly ReceiveMessageService receiveMessageService;

    public RequestsController(
        ReceiveMessageService receiveMessageService
    )
    {
        this.receiveMessageService = receiveMessageService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return Ok();
    }

    [HttpPost]
    public async Task<IActionResult> Index([FromForm] string manifest, [FromForm] IList<IFormFile> files)
    {
        // Process attachments
        var filesToProcess = await FileHelpers.ToFiles(files, ModelState);
        
        try
        {
            var returnMessageContent = await receiveMessageService.ReceiveRequest(manifest, filesToProcess, HttpContext.Response);
            return Created("requests", returnMessageContent);
        }
        catch(Exception ex)
        {
            return StatusCode((int)HttpStatusCode.InternalServerError, $"{ex.Message}\n\n{ex.StackTrace}\n\n{ex.InnerException?.Message}\n\n{ex.InnerException?.StackTrace}\n\nManifest sent:{manifest}");
        }
    }
}

src/EdNexusData.Broker.Web/Controllers/System/JobsController.cs
// Copyright: 2024 Education Nexus
// Author: Makoa Jacobsen, makoa@makoajacobsen.com

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EdNexusData.Broker.Web.Helpers;
using EdNexusData.Broker.Core.Worker;
using System.Linq.Expressions;
using EdNexusData.Broker.Web.Specifications;
using Ardalis.Specification;
using EdNexusData.Broker.Web.Models.Jobs;
using EdNexusData.Broker.Web.Models;
using EdNexusData.Broker.Web.Models.Paginations;
using Ardalis.GuardClauses;
using EdNexusData.Broker.Web.Constants.DesignSystems;
using EdNexusData.Broker.Web.Constants.Claims;
using EdNexusData.Broker.Data;
using Microsoft.EntityFrameworkCore;

namespace EdNexusData.Broker.Web.Controllers;

[Authorize]
public class JobsController : AuthenticatedController<JobsController>
{
    private readonly ILogger<JobsController> logger;
    private readonly IRepository<Job> jobsRepository;
    private readonly IRepository<User> userRepository;
    private readonly CurrentUserHelper currentUserHelper;
    private readonly FocusHelper focusHelper;
    private readonly JobService jobService;
    private readonly BrokerDbContext context;

    public JobsController(
        ILogger<JobsController> logger,
        IRepository<Job> jobsRepository,
        IRepository<User> userRepository,
        CurrentUserHelper currentUserHelper,
        FocusHelper focusHelper,
        JobService jobService,
        BrokerDbContext context)
    {
        this.logger = logger;
        this.jobsRepository = jobsRepository;
        this.userRepository = userRepository;
        this.currentUserHelper = currentUserHelper;
        this.focusHelper = focusHelper;
        this.jobService = jobService;
        this.context = context;
    }

    public async Task<IActionResult> Index(
        JobModel model,
        CancellationToken cancellationToken,
        Guid? jobId)
    {
        if (jobId is not null)
        {
            ViewBag.JobId = jobId;
        }

        var searchExpressions = new List<Expression<Func<Job, bool>>>
        {
            // Must restrict to currently logged in user
            x => x.CreatedBy == currentUserHelper.CurrentUserId()!.Value || x.InitiatedUserId == currentUserHelper.CurrentUserId()!.Value
        };

        searchExpressions = model.BuildSearchExpressions();

        var sortExpression = model.BuildSortExpression();

        var specification = new SearchableWithPaginationSpecification<Job>.Builder(model.Page, model.Size)
            .WithAscending((model.SortDir != null) ? model.IsAscending : false)
            .WithSortExpression(sortExpression)
            .WithSearchExpressions(searchExpressions)
            .WithIncludeEntities(builder => builder
                .Include(job => job.InitiatedUser)
            )
            .Build();

        var totalItems = await jobsRepository.CountAsync(
            specification,
            cancellationToken);

        var jobs = await jobsRepository.ListAsync(
            specification,
            cancellationToken);

        var jobsViewModels = jobs
            .Select(jobs => new JobViewModel(jobs, currentUserHelper.ResolvedCurrentUserTimeZone()));
        
        if (!string.IsNullOrWhiteSpace(model.SearchBy))
        {
            // jobsViewModels = jobsViewModels
            //     .Where(request => request.Student?.ToLower().Contains(model.SearchBy) is true || request.ReleasingDistrict.ToLower().Contains(model.SearchBy)
            //      || request.ReleasingSchool.ToLower().Contains(model.SearchBy));
            totalItems = jobsViewModels.Count();
        }

        var result = new PaginatedViewModel<JobViewModel>(
            jobsViewModels,
            totalItems,
            model.Page,
            model.Size,
            model.SortBy,
            model.SortDir,
            model.SearchBy);

        return View(result);
    }

    [Authorize(Policy = CustomClaimType.SystemAdministrator)]
    public async Task<IActionResult> SystemIndex(
        JobModel model,
        CancellationToken cancellationToken,
        Guid? jobId)
    {
        if (jobId is not null)
        {
            ViewBag.JobId = jobId;
        }

        var searchExpressions = new List<Expression<Func<Job, bool>>>();

        if (!focusHelper.IsEdOrgAllFocus()) {
            var focusedEdOrgs = await focusHelper.GetFocusedEdOrgs();
            searchExpressions.Add(
                u => u.CreatedByUser != null && u.CreatedByUser.UserRoles != null && u.CreatedByUser.UserRoles.Any(
                    r => focusedEdOrgs.Contains(r.EducationOrganization!)
                )
            );
            searchExpressions.Add(
                u => u.InitiatedUser != null && u.InitiatedUser.UserRoles != null && u.InitiatedUser.UserRoles.Any(
                    r => focusedEdOrgs.Contains(r.EducationOrganization!)
                )
            );
        }

        searchExpressions = model.BuildSearchExpressions();

        var sortExpression = model.BuildSortExpression();

        var specification = new SearchableWithPaginationSpecification<Job>.Builder(model.Page, model.Size)
            .WithAscending((model.SortDir != null) ? model.IsAscending : false)
            .WithSortExpression(sortExpression)
            .WithSearchExpressions(searchExpressions)
            .WithIncludeEntities(builder => builder
                .Include(job => job.InitiatedUser)
                .ThenInclude(x => x!.UserRoles)
                .Include(x => x.CreatedByUser)
                .ThenInclude(x => x!.UserRoles)
            )
            .Build();

        var totalItems = await jobsRepository.CountAsync(
            specification,
            cancellationToken);

        var jobs = await jobsRepository.ListAsync(
            specification,
            cancellationToken);

        var jobsViewModels = jobs
            .Select(jobs => new JobViewModel(jobs, currentUserHelper.ResolvedCurrentUserTimeZone()));
        
        if (!string.IsNullOrWhiteSpace(model.SearchBy))
        {
            // jobsViewModels = jobsViewModels
            //     .Where(request => request.Student?.ToLower().Contains(model.SearchBy) is true || request.ReleasingDistrict.ToLower().Contains(model.SearchBy)
            //      || request.ReleasingSchool.ToLower().Contains(model.SearchBy));
            totalItems = jobsViewModels.Count();
        }

        var result = new PaginatedViewModel<JobViewModel>(
            jobsViewModels,
            totalItems,
            model.Page,
            model.Size,
            model.SortBy,
            model.SortDir,
            model.SearchBy);

        return View("Index", result);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Restart(Guid id)
    {
        var job = await jobsRepository.GetByIdAsync(id);

        Guard.Against.Null(job, "job", "Unable to find job for Id");

        var jobType = AppDomain.CurrentDomain.GetAssemblies()
                            .SelectMany(s => s.GetExportedTypes())
                            .Where(p => p.FullName == job.JobType!).FirstOrDefault();

        Type? referenceType = null; 
        if (job.ReferenceType is not null)
        {
            referenceType = AppDomain.CurrentDomain.GetAssemblies()
                            .SelectMany(s => s.GetExportedTypes())
                            .Where(p => p.FullName == job.ReferenceType!).FirstOrDefault();
        }
        
        // Create job
        var createdJob = await jobService.CreateJobAsync(jobType!, referenceType, job.ReferenceGuid, job.InitiatedUserId, job.JobParameters);

        TempData[VoiceTone.Positive] = $"Restarting job ({job.Id}).";
        return RedirectToAction(nameof(Index), new { JobId = createdJob.Id });
    }

    public async Task<IActionResult> View(Guid id)
    {
        var job = await jobsRepository.GetByIdAsync(id);

        return View(job);
    }
}

src/EdNexusData.Broker.Web/Controllers/User/JobsController.cs
// Copyright: 2024 Education Nexus
// Author: Makoa Jacobsen, makoa@makoajacobsen.com

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EdNexusData.Broker.SharedKernel;
using EdNexusData.Broker.Web.Helpers;
using EdNexusData.Broker.Domain.Worker;
using System.Linq.Expressions;
using EdNexusData.Broker.Web.Specifications;
using Ardalis.Specification;
using EdNexusData.Broker.Web.Models.Jobs;
using EdNexusData.Broker.Web.Models;
using EdNexusData.Broker.Web.Models.Paginations;
using Ardalis.GuardClauses;
using EdNexusData.Broker.Service;
using EdNexusData.Broker.Web.Constants.DesignSystems;

namespace EdNexusData.Broker.Web.Controllers;

[Authorize]
public class JobsController : AuthenticatedController<JobsController>
{
    private readonly ILogger<JobsController> logger;
    private readonly IRepository<Job> jobsRepository;
    private readonly CurrentUserHelper currentUserHelper;
    private readonly JobService jobService;

    public JobsController(
        ILogger<JobsController> logger,
        IRepository<Job> jobsRepository,
        CurrentUserHelper currentUserHelper,
        JobService jobService)
    {
        this.logger = logger;
        this.jobsRepository = jobsRepository;
        this.currentUserHelper = currentUserHelper;
        this.jobService = jobService;
    }

    public async Task<IActionResult> Index(
        JobModel model,
        CancellationToken cancellationToken,
        Guid? jobId)
    {
        if (jobId is not null)
        {
            ViewBag.JobId = jobId;
        }

        var searchExpressions = new List<Expression<Func<Job, bool>>>
        {
            // Must restrict to currently logged in user
            x => x.CreatedBy == currentUserHelper.CurrentUserId()!.Value
        };

        searchExpressions = model.BuildSearchExpressions();

        var sortExpression = model.BuildSortExpression();

        var specification = new SearchableWithPaginationSpecification<Job>.Builder(model.Page, model.Size)
            .WithAscending((model.SortDir != null) ? model.IsAscending : false)
            .WithSortExpression(sortExpression)
            .WithSearchExpressions(searchExpressions)
            .Build();

        var totalItems = await jobsRepository.CountAsync(
            specification,
            cancellationToken);

        var jobs = await jobsRepository.ListAsync(
            specification,
            cancellationToken);

        var jobsViewModels = jobs
            .Select(jobs => new JobViewModel(jobs));
        
        if (!string.IsNullOrWhiteSpace(model.SearchBy))
        {
            // jobsViewModels = jobsViewModels
            //     .Where(request => request.Student?.ToLower().Contains(model.SearchBy) is true || request.ReleasingDistrict.ToLower().Contains(model.SearchBy)
            //      || request.ReleasingSchool.ToLower().Contains(model.SearchBy));
            totalItems = jobsViewModels.Count();
        }

        var result = new PaginatedViewModel<JobViewModel>(
            jobsViewModels,
            totalItems,
            model.Page,
            model.Size,
            model.SortBy,
            model.SortDir,
            model.SearchBy);

        return View(result);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Restart(Guid id)
    {
        var job = await jobsRepository.GetByIdAsync(id);

        Guard.Against.Null(job, "job", "Unable to find job for Id");

        var jobType = AppDomain.CurrentDomain.GetAssemblies()
                            .SelectMany(s => s.GetExportedTypes())
                            .Where(p => p.FullName == job.JobType!).FirstOrDefault();

        Type? referenceType = null; 
        if (job.ReferenceType is not null)
        {
            referenceType = AppDomain.CurrentDomain.GetAssemblies()
                            .SelectMany(s => s.GetExportedTypes())
                            .Where(p => p.FullName == job.ReferenceType!).FirstOrDefault();
        }
        
        // Create job
        var createdJob = await jobService.CreateJobAsync(jobType!, referenceType, job.ReferenceGuid);

        TempData[VoiceTone.Positive] = $"Restarting job ({job.Id}).";
        return RedirectToAction(nameof(Index), new { JobId = createdJob.Id });
    }

    public async Task<IActionResult> View(Guid id)
    {
        var job = await jobsRepository.GetByIdAsync(id);

        return View(job);
    }
}

src/EdNexusData.Broker.Web/Views/Jobs/View.cshtml
@model EdNexusData.Broker.Core.Worker.Job;
@using EdNexusData.Broker.Core.Extensions;
@using static EdNexusData.Broker.Web.Constants.Claims.CustomClaimType;
@using System.Text.Json;
@{
    // Copyright: 2023 Education Nexus Oregon
    // Author: Makoa Jacobsen, makoa@makoajacobsen.com
    ViewData["Title"] = "Job Detail";
    Layout = "_AuthenticatedLayout";
    ViewData["FocusBar"] = false;
    ViewData["FocusBarReadOnly"] = false;
}
<div class="space-y-10 divide-y divide-gray-900/10">
    <div class="px-4 sm:px-0">
        <div class="bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
            <div class="px-4 py-6 sm:p-8 grid gap-8">
                <div class="grid gap-6 border-b border-gray-900/10 pb-8">
                    <div>
                        <h2 class="text-base font-semibold leading-7 text-gray-900">Job Information</h2>
                        <p class="mt-1 text-sm leading-6 text-gray-600">Details of the job ran by the worker listed.</p>
                    </div>
                    <div class="grid grid-cols-1 gap-8 sm:grid-cols-8">
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Queued</label>
                            <div class="mt-2 text-gray-700">
                                @Model.QueueDateTime
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Started</label>
                            <div class="mt-2 text-gray-700">
                                @Model.StartDateTime
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Finished</label>
                            <div class="mt-2 text-gray-700">
                                @Model.FinishDateTime
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Status</label>
                            <div class="mt-2 text-gray-700">
                                @Model.JobStatus.GetDescription()
                            </div>
                        </div>
                    </div>
                    <div class="grid grid-cols-1 gap-8 sm:grid-cols-6">
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Reference Type</label>
                            <div class="mt-2 text-gray-700">
                                @Model.ReferenceType
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Reference Guid</label>
                            <div class="mt-2 text-gray-700">
                                @if (Model.ReferenceType == "EdNexusData.Broker.Core.Request")
                                {
                                    <a asp-controller="Requests" asp-action="View" asp-route-id="@Model.ReferenceGuid" class="text-tertiary-700 hover:text-tertiary-900">@Model.ReferenceGuid</a>
                                }
                                else
                                {
                                    @Model.ReferenceGuid
                                }
                            </div>
                        </div>
                        <div class="sm:col-span-2">
                            <label class="block text-sm font-medium leading-6 text-gray-900">Worker</label>
                            <div class="mt-2 text-gray-700">
                                @Model.WorkerInstance
                            </div>
                        </div>
                    </div>
                </div>
                <div class="grid gap-6 pb-8 border-b border-gray-900/10 ">
                    <div>
                        <h2 class="text-base font-semibold leading-7 text-gray-900">State</h2>
                    </div>
                    <div class="grid grid-cols-1 gap-6 sm:grid-cols-6">
                        <div class="sm:col-span-6">
                            <pre class="font-mono text-sm whitespace-pre-wrap">@Model.WorkerState</pre>
                        </div>
                    </div>
                </div>
                <div class="grid gap-6 pb-8">
                    <div>
                        <h2 class="text-base font-semibold leading-7 text-gray-900">Log</h2>
                    </div>
                    <div class="grid grid-cols-1 gap-6 sm:grid-cols-6">
                        <div class="sm:col-span-6">
                            <pre class="font-mono text-sm whitespace-pre-wrap">@Model.WorkerLog</pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section HeaderAction
{
<form asp-controller="Jobs" asp-action="Restart" asp-route-id="@Model.Id" class="inline">
    <button type="submit" role="menuitem" tabindex="-1" id="user-menu-item-2" class="relative inline-flex items-center rounded-md bg-tertiary-700 px-3 py-2 text-center text-sm font-semibold ring-1 ring-inset ring-tertiary-800 text-white shadow-sm hover:bg-tertiary-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tertiary-700 focus:z-10">Restart</button>
</form>
}